Update README file and remove unnecessary log dependency
lunny/axmlParser pull request #7
Opened 2018-04-13 16:17 UTC by jimmyjjames

Update README file and remove unnecessary log dependency

2018-04-14 11:56 UTC, lunny requested changes

2018-04-14 11:56 UTC, lunny commented on README.md
> +	fmt.Printf("VersionCode: %v\n", listener.VersionName)
VersionName

2018-04-16 11:00 UTC, jimmyjjames commented
Have done the change.

2018-04-16 14:51 UTC, lunny approved these changes

2018-04-16 14:53 UTC, merged